nntpit: Add XOVER and LIST OVERVIEW.FMT.
taviso/nntpit pull request #12
Opened 2022-03-20 11:27 UTC by daym

This adds support for `XOVER` and some initial support for `LIST OVERVIEW.FMT`. The latter is specified by the RFC as "should implement when implementing XOVER".

2022-03-20 15:12 UTC, taviso commented
wow, thanks! I tried it out, but slrn sends `XOVER` without any parameter, and that crashes with a `NULL` `param` here:

```c
    int beginning = strtol(param, &endptr, 10);

```

I'm not sure what the server is supposed to send back, I need to refresh my nntp memory.

2022-03-20 17:40 UTC, daym commented
https://datatracker.ietf.org/doc/html/rfc2980#section-2.8 says 

>   If no argument is specified, then information from the current article is displayed.  

What is the "current" article?

2022-03-20 18:11 UTC, taviso commented
Ahh - that seems fine to me! It doesn't crash anymore, but slrn doesn't like the field names. It says:


```
OVERVIEW.FMT not RFC 2980 compliant -- XOVER support disabled.
```

This seems to work though:

```c
        client_printf(cl, "215 information follows\r\n");
        // TODO: What are the field names usually used here?
        client_printf(cl, "subject\r\n");
        client_printf(cl, "from\r\n");
        client_printf(cl, "date\r\n");
        client_printf(cl, "message-id\r\n");
        client_printf(cl, "references\r\n");
        client_printf(cl, "bytes\n");
        client_printf(cl, "lines\r\n");
        client_printf(cl, ".\r\n");
```

Can you see if that works with your client too? (You still need to send the article number, just not include it in the overview).

2022-03-20 18:12 UTC, taviso commented
If that works for you too, I see no reason not to merge for now...

I'm not sure if the line and byte count should be accurate, or maybe we will confuse someone... but confusing them seems better than not working at all!

2022-03-20 18:14 UTC, daym commented
Yeah, it works for my reader too without `number` in the overview.

2022-03-20 18:15 UTC, daym commented
Yeah, these line and byte counts are too much work and I don't see what those would be for in the first place... Ideal would be if there's a value to use for "don't know".

2022-03-20 19:24 UTC, taviso requested changes

2022-03-20 19:24 UTC, taviso commented on nntpit.c
> +        client_printf(cl, "author\r\n");
author should be "from"

2022-03-20 19:24 UTC, taviso commented on nntpit.c
> +        client_printf(cl, "line-count\r\n");
These should "bytes" and "lines", and then I guess it's safe to remove the TODO because these seem to be the correct field names!

2022-03-21 22:28 UTC, merged

2022-03-21 22:29 UTC, taviso commented
Looks good to me - thanks!!